services:
  - type: web
    name: survey-dashboard-backend
    env: python
    region: singapore
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    rootDir: backend
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
